//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioReservaPeliculas.ServiceReference_Reserva {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_Reserva.ReservaSoap")]
    public interface ReservaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechaSeleccionada del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarReserva", ReplyAction="*")]
        SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaResponse registrarReserva(SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarReserva", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaResponse> registrarReservaAsync(SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento listarClientesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarClientes", ReplyAction="*")]
        SitioReservaPeliculas.ServiceReference_Reserva.listarClientesResponse listarClientes(SitioReservaPeliculas.ServiceReference_Reserva.listarClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.listarClientesResponse> listarClientesAsync(SitioReservaPeliculas.ServiceReference_Reserva.listarClientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento listarPeliculasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarPeliculas", ReplyAction="*")]
        SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasResponse listarPeliculas(SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarPeliculas", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasResponse> listarPeliculasAsync(SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento condicion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerReserva", ReplyAction="*")]
        SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaResponse TraerReserva(SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerReserva", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaResponse> TraerReservaAsync(SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento eliminarReservaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarReserva", ReplyAction="*")]
        SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaResponse eliminarReserva(SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarReserva", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaResponse> eliminarReservaAsync(SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificarReserva", ReplyAction="*")]
        SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaResponse modificarReserva(SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificarReserva", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaResponse> modificarReservaAsync(SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularPrecioTotal", ReplyAction="*")]
        decimal CalcularPrecioTotal(int idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularPrecioTotal", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> CalcularPrecioTotalAsync(int idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTotalReservasRegistradas", ReplyAction="*")]
        int ObtenerTotalReservasRegistradas(int idCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTotalReservasRegistradas", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ObtenerTotalReservasRegistradasAsync(int idCliente);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerNombrePeliculaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerNombrePelicula", ReplyAction="*")]
        SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaResponse ObtenerNombrePelicula(SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerNombrePelicula", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaResponse> ObtenerNombrePeliculaAsync(SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarReserva", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaRequestBody Body;
        
        public registrarReservaRequest() {
        }
        
        public registrarReservaRequest(SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarReservaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechaSeleccionada;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hora;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pelicula;
        
        public registrarReservaRequestBody() {
        }
        
        public registrarReservaRequestBody(int cliente, string fechaSeleccionada, string hora, int pelicula) {
            this.cliente = cliente;
            this.fechaSeleccionada = fechaSeleccionada;
            this.hora = hora;
            this.pelicula = pelicula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarReservaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaResponseBody Body;
        
        public registrarReservaResponse() {
        }
        
        public registrarReservaResponse(SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarReservaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registrarReservaResult;
        
        public registrarReservaResponseBody() {
        }
        
        public registrarReservaResponseBody(string registrarReservaResult) {
            this.registrarReservaResult = registrarReservaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarClientes", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Reserva.listarClientesRequestBody Body;
        
        public listarClientesRequest() {
        }
        
        public listarClientesRequest(SitioReservaPeliculas.ServiceReference_Reserva.listarClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarClientesRequestBody {
        
        public listarClientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarClientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Reserva.listarClientesResponseBody Body;
        
        public listarClientesResponse() {
        }
        
        public listarClientesResponse(SitioReservaPeliculas.ServiceReference_Reserva.listarClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listarClientesResult;
        
        public listarClientesResponseBody() {
        }
        
        public listarClientesResponseBody(string listarClientesResult) {
            this.listarClientesResult = listarClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarPeliculasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarPeliculas", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasRequestBody Body;
        
        public listarPeliculasRequest() {
        }
        
        public listarPeliculasRequest(SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarPeliculasRequestBody {
        
        public listarPeliculasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarPeliculasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarPeliculasResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasResponseBody Body;
        
        public listarPeliculasResponse() {
        }
        
        public listarPeliculasResponse(SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarPeliculasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listarPeliculasResult;
        
        public listarPeliculasResponseBody() {
        }
        
        public listarPeliculasResponseBody(string listarPeliculasResult) {
            this.listarPeliculasResult = listarPeliculasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraerReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraerReserva", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaRequestBody Body;
        
        public TraerReservaRequest() {
        }
        
        public TraerReservaRequest(SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraerReservaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string condicion;
        
        public TraerReservaRequestBody() {
        }
        
        public TraerReservaRequestBody(string condicion) {
            this.condicion = condicion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraerReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraerReservaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaResponseBody Body;
        
        public TraerReservaResponse() {
        }
        
        public TraerReservaResponse(SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraerReservaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TraerReservaResult;
        
        public TraerReservaResponseBody() {
        }
        
        public TraerReservaResponseBody(string TraerReservaResult) {
            this.TraerReservaResult = TraerReservaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarReserva", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaRequestBody Body;
        
        public eliminarReservaRequest() {
        }
        
        public eliminarReservaRequest(SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarReservaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int íd;
        
        public eliminarReservaRequestBody() {
        }
        
        public eliminarReservaRequestBody(int íd) {
            this.íd = íd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarReservaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaResponseBody Body;
        
        public eliminarReservaResponse() {
        }
        
        public eliminarReservaResponse(SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarReservaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string eliminarReservaResult;
        
        public eliminarReservaResponseBody() {
        }
        
        public eliminarReservaResponseBody(string eliminarReservaResult) {
            this.eliminarReservaResult = eliminarReservaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarReserva", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaRequestBody Body;
        
        public modificarReservaRequest() {
        }
        
        public modificarReservaRequest(SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarReservaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string hora;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pelicula;
        
        public modificarReservaRequestBody() {
        }
        
        public modificarReservaRequestBody(int id, int cliente, string fecha, string hora, int pelicula) {
            this.id = id;
            this.cliente = cliente;
            this.fecha = fecha;
            this.hora = hora;
            this.pelicula = pelicula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarReservaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaResponseBody Body;
        
        public modificarReservaResponse() {
        }
        
        public modificarReservaResponse(SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarReservaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string modificarReservaResult;
        
        public modificarReservaResponseBody() {
        }
        
        public modificarReservaResponseBody(string modificarReservaResult) {
            this.modificarReservaResult = modificarReservaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerNombrePeliculaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerNombrePelicula", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaRequestBody Body;
        
        public ObtenerNombrePeliculaRequest() {
        }
        
        public ObtenerNombrePeliculaRequest(SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerNombrePeliculaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idPelicula;
        
        public ObtenerNombrePeliculaRequestBody() {
        }
        
        public ObtenerNombrePeliculaRequestBody(int idPelicula) {
            this.idPelicula = idPelicula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerNombrePeliculaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerNombrePeliculaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaResponseBody Body;
        
        public ObtenerNombrePeliculaResponse() {
        }
        
        public ObtenerNombrePeliculaResponse(SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerNombrePeliculaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerNombrePeliculaResult;
        
        public ObtenerNombrePeliculaResponseBody() {
        }
        
        public ObtenerNombrePeliculaResponseBody(string ObtenerNombrePeliculaResult) {
            this.ObtenerNombrePeliculaResult = ObtenerNombrePeliculaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReservaSoapChannel : SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservaSoapClient : System.ServiceModel.ClientBase<SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap>, SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap {
        
        public ReservaSoapClient() {
        }
        
        public ReservaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaResponse SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap.registrarReserva(SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaRequest request) {
            return base.Channel.registrarReserva(request);
        }
        
        public string registrarReserva(int cliente, string fechaSeleccionada, string hora, int pelicula) {
            SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaRequest inValue = new SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.fechaSeleccionada = fechaSeleccionada;
            inValue.Body.hora = hora;
            inValue.Body.pelicula = pelicula;
            SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaResponse retVal = ((SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap)(this)).registrarReserva(inValue);
            return retVal.Body.registrarReservaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaResponse> SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap.registrarReservaAsync(SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaRequest request) {
            return base.Channel.registrarReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaResponse> registrarReservaAsync(int cliente, string fechaSeleccionada, string hora, int pelicula) {
            SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaRequest inValue = new SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Reserva.registrarReservaRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.fechaSeleccionada = fechaSeleccionada;
            inValue.Body.hora = hora;
            inValue.Body.pelicula = pelicula;
            return ((SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap)(this)).registrarReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioReservaPeliculas.ServiceReference_Reserva.listarClientesResponse SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap.listarClientes(SitioReservaPeliculas.ServiceReference_Reserva.listarClientesRequest request) {
            return base.Channel.listarClientes(request);
        }
        
        public string listarClientes() {
            SitioReservaPeliculas.ServiceReference_Reserva.listarClientesRequest inValue = new SitioReservaPeliculas.ServiceReference_Reserva.listarClientesRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Reserva.listarClientesRequestBody();
            SitioReservaPeliculas.ServiceReference_Reserva.listarClientesResponse retVal = ((SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap)(this)).listarClientes(inValue);
            return retVal.Body.listarClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.listarClientesResponse> SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap.listarClientesAsync(SitioReservaPeliculas.ServiceReference_Reserva.listarClientesRequest request) {
            return base.Channel.listarClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.listarClientesResponse> listarClientesAsync() {
            SitioReservaPeliculas.ServiceReference_Reserva.listarClientesRequest inValue = new SitioReservaPeliculas.ServiceReference_Reserva.listarClientesRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Reserva.listarClientesRequestBody();
            return ((SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap)(this)).listarClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasResponse SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap.listarPeliculas(SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasRequest request) {
            return base.Channel.listarPeliculas(request);
        }
        
        public string listarPeliculas() {
            SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasRequest inValue = new SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasRequestBody();
            SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasResponse retVal = ((SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap)(this)).listarPeliculas(inValue);
            return retVal.Body.listarPeliculasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasResponse> SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap.listarPeliculasAsync(SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasRequest request) {
            return base.Channel.listarPeliculasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasResponse> listarPeliculasAsync() {
            SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasRequest inValue = new SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Reserva.listarPeliculasRequestBody();
            return ((SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap)(this)).listarPeliculasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaResponse SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap.TraerReserva(SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaRequest request) {
            return base.Channel.TraerReserva(request);
        }
        
        public string TraerReserva(string condicion) {
            SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaRequest inValue = new SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaRequestBody();
            inValue.Body.condicion = condicion;
            SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaResponse retVal = ((SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap)(this)).TraerReserva(inValue);
            return retVal.Body.TraerReservaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaResponse> SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap.TraerReservaAsync(SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaRequest request) {
            return base.Channel.TraerReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaResponse> TraerReservaAsync(string condicion) {
            SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaRequest inValue = new SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Reserva.TraerReservaRequestBody();
            inValue.Body.condicion = condicion;
            return ((SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap)(this)).TraerReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaResponse SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap.eliminarReserva(SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaRequest request) {
            return base.Channel.eliminarReserva(request);
        }
        
        public string eliminarReserva(int íd) {
            SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaRequest inValue = new SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaRequestBody();
            inValue.Body.íd = íd;
            SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaResponse retVal = ((SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap)(this)).eliminarReserva(inValue);
            return retVal.Body.eliminarReservaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaResponse> SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap.eliminarReservaAsync(SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaRequest request) {
            return base.Channel.eliminarReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaResponse> eliminarReservaAsync(int íd) {
            SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaRequest inValue = new SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Reserva.eliminarReservaRequestBody();
            inValue.Body.íd = íd;
            return ((SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap)(this)).eliminarReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaResponse SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap.modificarReserva(SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaRequest request) {
            return base.Channel.modificarReserva(request);
        }
        
        public string modificarReserva(int id, int cliente, string fecha, string hora, int pelicula) {
            SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaRequest inValue = new SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaRequestBody();
            inValue.Body.id = id;
            inValue.Body.cliente = cliente;
            inValue.Body.fecha = fecha;
            inValue.Body.hora = hora;
            inValue.Body.pelicula = pelicula;
            SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaResponse retVal = ((SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap)(this)).modificarReserva(inValue);
            return retVal.Body.modificarReservaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaResponse> SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap.modificarReservaAsync(SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaRequest request) {
            return base.Channel.modificarReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaResponse> modificarReservaAsync(int id, int cliente, string fecha, string hora, int pelicula) {
            SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaRequest inValue = new SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Reserva.modificarReservaRequestBody();
            inValue.Body.id = id;
            inValue.Body.cliente = cliente;
            inValue.Body.fecha = fecha;
            inValue.Body.hora = hora;
            inValue.Body.pelicula = pelicula;
            return ((SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap)(this)).modificarReservaAsync(inValue);
        }
        
        public decimal CalcularPrecioTotal(int idCliente) {
            return base.Channel.CalcularPrecioTotal(idCliente);
        }
        
        public System.Threading.Tasks.Task<decimal> CalcularPrecioTotalAsync(int idCliente) {
            return base.Channel.CalcularPrecioTotalAsync(idCliente);
        }
        
        public int ObtenerTotalReservasRegistradas(int idCliente) {
            return base.Channel.ObtenerTotalReservasRegistradas(idCliente);
        }
        
        public System.Threading.Tasks.Task<int> ObtenerTotalReservasRegistradasAsync(int idCliente) {
            return base.Channel.ObtenerTotalReservasRegistradasAsync(idCliente);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaResponse SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap.ObtenerNombrePelicula(SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaRequest request) {
            return base.Channel.ObtenerNombrePelicula(request);
        }
        
        public string ObtenerNombrePelicula(int idPelicula) {
            SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaRequest inValue = new SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaRequestBody();
            inValue.Body.idPelicula = idPelicula;
            SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaResponse retVal = ((SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap)(this)).ObtenerNombrePelicula(inValue);
            return retVal.Body.ObtenerNombrePeliculaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaResponse> SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap.ObtenerNombrePeliculaAsync(SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaRequest request) {
            return base.Channel.ObtenerNombrePeliculaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaResponse> ObtenerNombrePeliculaAsync(int idPelicula) {
            SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaRequest inValue = new SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Reserva.ObtenerNombrePeliculaRequestBody();
            inValue.Body.idPelicula = idPelicula;
            return ((SitioReservaPeliculas.ServiceReference_Reserva.ReservaSoap)(this)).ObtenerNombrePeliculaAsync(inValue);
        }
    }
}
