//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioReservaPeliculas.ServiceReference_Usuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_Usuario.UsuarioSoap")]
    public interface UsuarioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarUsuario", ReplyAction="*")]
        SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioResponse registrarUsuario(SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioResponse> registrarUsuarioAsync(SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioRequestBody Body;
        
        public registrarUsuarioRequest() {
        }
        
        public registrarUsuarioRequest(SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string clave;
        
        public registrarUsuarioRequestBody() {
        }
        
        public registrarUsuarioRequestBody(string nombre, string apellido, string email, string clave) {
            this.nombre = nombre;
            this.apellido = apellido;
            this.email = email;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioResponseBody Body;
        
        public registrarUsuarioResponse() {
        }
        
        public registrarUsuarioResponse(SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registrarUsuarioResult;
        
        public registrarUsuarioResponseBody() {
        }
        
        public registrarUsuarioResponseBody(string registrarUsuarioResult) {
            this.registrarUsuarioResult = registrarUsuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsuarioSoapChannel : SitioReservaPeliculas.ServiceReference_Usuario.UsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioSoapClient : System.ServiceModel.ClientBase<SitioReservaPeliculas.ServiceReference_Usuario.UsuarioSoap>, SitioReservaPeliculas.ServiceReference_Usuario.UsuarioSoap {
        
        public UsuarioSoapClient() {
        }
        
        public UsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioResponse SitioReservaPeliculas.ServiceReference_Usuario.UsuarioSoap.registrarUsuario(SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioRequest request) {
            return base.Channel.registrarUsuario(request);
        }
        
        public string registrarUsuario(string nombre, string apellido, string email, string clave) {
            SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioRequest inValue = new SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.email = email;
            inValue.Body.clave = clave;
            SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioResponse retVal = ((SitioReservaPeliculas.ServiceReference_Usuario.UsuarioSoap)(this)).registrarUsuario(inValue);
            return retVal.Body.registrarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioResponse> SitioReservaPeliculas.ServiceReference_Usuario.UsuarioSoap.registrarUsuarioAsync(SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioRequest request) {
            return base.Channel.registrarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioResponse> registrarUsuarioAsync(string nombre, string apellido, string email, string clave) {
            SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioRequest inValue = new SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Usuario.registrarUsuarioRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.email = email;
            inValue.Body.clave = clave;
            return ((SitioReservaPeliculas.ServiceReference_Usuario.UsuarioSoap)(this)).registrarUsuarioAsync(inValue);
        }
    }
}
