//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioReservaPeliculas.ServiceReference_Categoria {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_Categoria.CategoriaSoap")]
    public interface CategoriaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCategoria", ReplyAction="*")]
        SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaResponse registrarCategoria(SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaResponse> registrarCategoriaAsync(SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento condicion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCategoria", ReplyAction="*")]
        SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaResponse TraerCategoria(SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaResponse> TraerCategoriaAsync(SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento eliminarCategoriaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarCategoria", ReplyAction="*")]
        SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaResponse eliminarCategoria(SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaResponse> eliminarCategoriaAsync(SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificarCategoria", ReplyAction="*")]
        SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaResponse modificarCategoria(SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificarCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaResponse> modificarCategoriaAsync(SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCategoria", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaRequestBody Body;
        
        public registrarCategoriaRequest() {
        }
        
        public registrarCategoriaRequest(SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCategoriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public registrarCategoriaRequestBody() {
        }
        
        public registrarCategoriaRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCategoriaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaResponseBody Body;
        
        public registrarCategoriaResponse() {
        }
        
        public registrarCategoriaResponse(SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCategoriaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registrarCategoriaResult;
        
        public registrarCategoriaResponseBody() {
        }
        
        public registrarCategoriaResponseBody(string registrarCategoriaResult) {
            this.registrarCategoriaResult = registrarCategoriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraerCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraerCategoria", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaRequestBody Body;
        
        public TraerCategoriaRequest() {
        }
        
        public TraerCategoriaRequest(SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraerCategoriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string condicion;
        
        public TraerCategoriaRequestBody() {
        }
        
        public TraerCategoriaRequestBody(string condicion) {
            this.condicion = condicion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraerCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraerCategoriaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaResponseBody Body;
        
        public TraerCategoriaResponse() {
        }
        
        public TraerCategoriaResponse(SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraerCategoriaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TraerCategoriaResult;
        
        public TraerCategoriaResponseBody() {
        }
        
        public TraerCategoriaResponseBody(string TraerCategoriaResult) {
            this.TraerCategoriaResult = TraerCategoriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarCategoria", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaRequestBody Body;
        
        public eliminarCategoriaRequest() {
        }
        
        public eliminarCategoriaRequest(SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarCategoriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int íd;
        
        public eliminarCategoriaRequestBody() {
        }
        
        public eliminarCategoriaRequestBody(int íd) {
            this.íd = íd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarCategoriaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaResponseBody Body;
        
        public eliminarCategoriaResponse() {
        }
        
        public eliminarCategoriaResponse(SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarCategoriaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string eliminarCategoriaResult;
        
        public eliminarCategoriaResponseBody() {
        }
        
        public eliminarCategoriaResponseBody(string eliminarCategoriaResult) {
            this.eliminarCategoriaResult = eliminarCategoriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarCategoria", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaRequestBody Body;
        
        public modificarCategoriaRequest() {
        }
        
        public modificarCategoriaRequest(SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarCategoriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        public modificarCategoriaRequestBody() {
        }
        
        public modificarCategoriaRequestBody(int id, string nombre) {
            this.id = id;
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarCategoriaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaResponseBody Body;
        
        public modificarCategoriaResponse() {
        }
        
        public modificarCategoriaResponse(SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarCategoriaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string modificarCategoriaResult;
        
        public modificarCategoriaResponseBody() {
        }
        
        public modificarCategoriaResponseBody(string modificarCategoriaResult) {
            this.modificarCategoriaResult = modificarCategoriaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CategoriaSoapChannel : SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoriaSoapClient : System.ServiceModel.ClientBase<SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap>, SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap {
        
        public CategoriaSoapClient() {
        }
        
        public CategoriaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaResponse SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap.registrarCategoria(SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaRequest request) {
            return base.Channel.registrarCategoria(request);
        }
        
        public string registrarCategoria(string nombre) {
            SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaRequest inValue = new SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaRequestBody();
            inValue.Body.nombre = nombre;
            SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaResponse retVal = ((SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap)(this)).registrarCategoria(inValue);
            return retVal.Body.registrarCategoriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaResponse> SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap.registrarCategoriaAsync(SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaRequest request) {
            return base.Channel.registrarCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaResponse> registrarCategoriaAsync(string nombre) {
            SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaRequest inValue = new SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Categoria.registrarCategoriaRequestBody();
            inValue.Body.nombre = nombre;
            return ((SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap)(this)).registrarCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaResponse SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap.TraerCategoria(SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaRequest request) {
            return base.Channel.TraerCategoria(request);
        }
        
        public string TraerCategoria(string condicion) {
            SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaRequest inValue = new SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaRequestBody();
            inValue.Body.condicion = condicion;
            SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaResponse retVal = ((SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap)(this)).TraerCategoria(inValue);
            return retVal.Body.TraerCategoriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaResponse> SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap.TraerCategoriaAsync(SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaRequest request) {
            return base.Channel.TraerCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaResponse> TraerCategoriaAsync(string condicion) {
            SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaRequest inValue = new SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Categoria.TraerCategoriaRequestBody();
            inValue.Body.condicion = condicion;
            return ((SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap)(this)).TraerCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaResponse SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap.eliminarCategoria(SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaRequest request) {
            return base.Channel.eliminarCategoria(request);
        }
        
        public string eliminarCategoria(int íd) {
            SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaRequest inValue = new SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaRequestBody();
            inValue.Body.íd = íd;
            SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaResponse retVal = ((SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap)(this)).eliminarCategoria(inValue);
            return retVal.Body.eliminarCategoriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaResponse> SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap.eliminarCategoriaAsync(SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaRequest request) {
            return base.Channel.eliminarCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaResponse> eliminarCategoriaAsync(int íd) {
            SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaRequest inValue = new SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Categoria.eliminarCategoriaRequestBody();
            inValue.Body.íd = íd;
            return ((SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap)(this)).eliminarCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaResponse SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap.modificarCategoria(SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaRequest request) {
            return base.Channel.modificarCategoria(request);
        }
        
        public string modificarCategoria(int id, string nombre) {
            SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaRequest inValue = new SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaRequestBody();
            inValue.Body.id = id;
            inValue.Body.nombre = nombre;
            SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaResponse retVal = ((SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap)(this)).modificarCategoria(inValue);
            return retVal.Body.modificarCategoriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaResponse> SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap.modificarCategoriaAsync(SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaRequest request) {
            return base.Channel.modificarCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaResponse> modificarCategoriaAsync(int id, string nombre) {
            SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaRequest inValue = new SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaRequest();
            inValue.Body = new SitioReservaPeliculas.ServiceReference_Categoria.modificarCategoriaRequestBody();
            inValue.Body.id = id;
            inValue.Body.nombre = nombre;
            return ((SitioReservaPeliculas.ServiceReference_Categoria.CategoriaSoap)(this)).modificarCategoriaAsync(inValue);
        }
    }
}
